#ifndef TESEO_HAL_DEFAULT_CONFIG_H
#define TESEO_HAL_DEFAULT_CONFIG_H

#define CFG_DEF_DEVICE_TTY std::string("/dev/ttyAMA2")

#define CFG_DEF_STAGPS_ENABLE false

#define CFG_DEF_STAGPS_PREDICTIVE_ENABLE    false
#define CFG_DEF_STAGPS_PREDICTIVE_HOST      std::string("")
#define CFG_DEF_STAGPS_PREDICTIVE_PORT      0
#define CFG_DEF_STAGPS_PREDICTIVE_MODEL_ID  std::string("")
#define CFG_DEF_STAGPS_PREDICTIVE_DEVICE_ID std::string("")
#define CFG_DEF_STAGPS_PREDICTIVE_SEED_TYPE 14
#define CFG_DEF_STAGPS_PREDICTIVE_BASE_PATH std::string("")

#endif // TESEO_HAL_DEFAULT_CONFIG_H